receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch: {}

  resource:
    attributes:
      - key: service.name
        value: dotnet-service
        action: insert

exporters:
  otlp:
    endpoint: hyperdx:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp]
